create table block_chain (id bigint not null auto_increment, initial_date_time TIMESTAMP not null, final_date_time TIMESTAMP not null, primary key (id)) engine=InnoDB;
create table client (balance_amount double precision not null, id bigint not null, primary key (id)) engine=InnoDB;
create table employee (admission_date datetime(6) not null, resignation_date datetime(6), salary double precision not null, id bigint not null, role_id integer not null, primary key (id)) engine=InnoDB;
create table payment (id bigint not null auto_increment, date_time TIMESTAMP not null, status integer not null, block_chain_id bigint not null, smart_contract_id bigint not null, primary key (id)) engine=InnoDB;
create table role (id integer not null auto_increment, description TEXT not null, primary key (id)) engine=InnoDB;
create table service (id bigint not null auto_increment, description TEXT not null, final_date_time datetime(6), initial_date_time datetime(6) not null, number_hours_of_service integer, service_status integer not null, client_id bigint not null, service_provider_id bigint, primary key (id)) engine=InnoDB;
create table service_provider (curriculum_uri TEXT not null, description TEXT not null, profession varchar(255) not null, id bigint not null, primary key (id)) engine=InnoDB;
create table service_provider_request_services (service_provider_id bigint not null, request_services_id bigint not null, primary key (service_provider_id, request_services_id)) engine=InnoDB;
create table smart_contract (id bigint not null auto_increment, contract_value double precision not null, contracted_signature varchar(255) not null, customer_signature varchar(255) not null, block_chain_id bigint not null, service_provider_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, cnpj varchar(255), cpf varchar(255), address varchar(255) not null, birthdate datetime(6) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
alter table payment add constraint UK_eyfcaayvcdtddqs4yy7psjyq4 unique (smart_contract_id);
alter table service_provider_request_services add constraint UK_jdlvbs7i46cfx5bmg75x1vh2c unique (request_services_id);
alter table user add constraint UK_3u5qmcnigcywkeko72ryh4haa unique (cnpj);
alter table user add constraint UK_2qv8vmk5wxu215bevli5derq unique (cpf);
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table client add constraint FK4ai00u1wkkeysdaq92yicsf6e foreign key (id) references user (id);
alter table employee add constraint FK3046kvjyysq288vy3lsbtc9nw foreign key (role_id) references role (id);
alter table employee add constraint FKd8il4lxw1wi74qh8b7uoy6e0a foreign key (id) references user (id);
alter table payment add constraint FKn86ojgysfot96otchhpktfn1u foreign key (block_chain_id) references block_chain (id);
alter table payment add constraint FKi15iiv5g376d1qogly8ogq2r4 foreign key (smart_contract_id) references smart_contract (id);
alter table service add constraint FKa89liam8scj4xb024po8d25f8 foreign key (client_id) references client (id);
alter table service add constraint FKejlr1wmwdlfbcfb6y51yd1os6 foreign key (service_provider_id) references service_provider (id);
alter table service_provider add constraint FKm8yrshhni7cc65o1v0cqdfmud foreign key (id) references user (id);
alter table service_provider_request_services add constraint FKfws0bnaq6ptu153tsqd55mbhc foreign key (request_services_id) references service (id);
alter table service_provider_request_services add constraint FK72ignm5eou0xc83riekj6nac foreign key (service_provider_id) references service_provider (id);
alter table smart_contract add constraint FKt6brsdbbigi97hqxxtc3cluy foreign key (block_chain_id) references block_chain (id);
alter table smart_contract add constraint FKdc73jblso0yencvhv7q3d6edr foreign key (service_provider_id) references service_provider (id);
alter table smart_contract add constraint FKqy9865khv0j46o633knp74cpq foreign key (user_id) references user (id);
